name: Notify Discord on Push

on:
  push:
    branches:
      - "**"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord message
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"📌 New push in **${{ github.repository }}** by \`${{ github.actor }}\`\nCommit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}\"}" \
            $WEBHOOK_URL
